# Gunakan Nginx bertipe alpine yang sangat ringan
FROM nginx:alpine

# Copy konten HTML/CSS/JS ke folder root Nginx
COPY . /usr/share/nginx/html

# Expose port (default nginx adalah 80)
EXPOSE 80
